version: 2

sources:
  - name: ecommerce
    description: "Dados da loja de E-commerce"
    schema: dbt_dw_raw
    loader: bigquery
    
    tables: 
      - name: avaliacoes
        description: "Tabela de avaliações dos produtos"
        columns:
          - name: cliente_id
            description: "ID do cliente que fez a avaliação"
            data_teste:
              - name: not_null
          - name: produto_id
            description: "ID do produto avaliado"
            data_teste:
              - name: not_null
          - name: nota
            description: "Nota da avaliação"
          - name: comentario
            description: "Comentário da avaliação"
          - name: data_avaliacao
            description: "Data da avaliação"

      - name: carrinho
        description: "Tabela de carrinhos de compras"
        columns:
          - name: cliente_id
            description: "ID do cliente que fez a compra"
            data_teste:
              - name: not_null
          - name: produto_id
            description: "ID do produto comprado"
            data_teste:
              - name: not_null
          - name: quantidade
            description: "Quantidade do produto comprado"
            data_teste:
              - name: not_null
          - name: data_adicionado
            description: "Data do carrinho"
      - name: categorias
        description: "Tabela de categorias dos produtos"
        columns:
          - name: id
            description: "ID da categoria"
            data_teste:
              - name: not_null
              - name: unique
          - name: nome
            description: "Nome da categoria"
      - name: clientes
        description: "Tabela de clientes"
        columns:
          - name: id
            description: "ID do cliente"
            data_teste:
              - name: not_null
              - name: unique
          - name: nome
            description: "Nome do cliente"
          - name: email
            description: "Email do cliente"
            data_teste:
              - valid_email
          - name: telefone
            description: "Telefone do cliente"
          - name: data_registro
            description: "Data de cadastro do cliente"
      - name: itens_pedidos
        description: "Tabela de itens dos pedidos"
        columns:
          - name: pedido_id
            description: "Chave extrangeira do pedido"
            data_tests:
              - not_null
          - name: produto_id
            description: "Chave extrangeira do produto"
            data_tests:
              - not_null
          - name: quantidade
            description: "Quantidade do produto"
          - name: preco_unitario
            description: "Preço unitário do produto"
          - name: subtotal
            description: "Subtotal do item do pedido"

      - name: pagamentos
        description: "Tabela de pagamentos"
        columns:
          - name: id
            description: "Chave primária do pagamento"
            data_tests:
              - not_null
              - unique
          - name: pedido_id
            description: "Chave extrangeira do pedido"
            data_tests:
              - not_null
          - name: valor
            description: "Valor do pagamento"
          - name: metodo
            description: "Método de pagamento"
          - name: status
            description: "Status do pagamento"
          - name: data_pagamento
            description: "Data do pagamento"

      - name: pedidos
        description: "Tabela de pedidos"
        columns:
          - name: id
            description: "Chave primária do pedido"
            data_tests:
              - not_null
              - unique
          - name: cliente_id
            description: "Chave extrangeira do cliente"
            data_tests:
              - not_null
          - name: endereco_id
            description: "Chave extrangeira do endereço de entrega"
            data_tests:
              - not_null
          - name: data_pedido
            description: "Data do pedido"
          - name: status
            description: "Status do pedido"

      - name: produtos
        description: "Tabela de produtos"
        columns:
          - name: id
            description: "Chave primária do produto"
            data_tests:
              - not_null
              - unique
          - name: nome
            description: "Nome do produto"
          - name: descricao
            description: "Descrição do produto"
          - name: categoria_id
            description: "Chave extrangeira da categoria do produto"
            data_tests:
              - not_null
          - name: preco
            description: "Preço do produto"
          - name: marca
            description: "Marca do produto"
          - name: estoque
            description: "Quantidade em estoque"
          - name: data_cadastro
            description: "Data de cadastro do produto"